#!/usr/bin/env bash
usrDir=/usr/local/bin

printf "\nDownloading chalk (Terminal coloring library)...\n"

#Terminal coloring library
npm install --global chalk-cli

printf "\n\n"

#If swim directory does not exist
if [ ! -d "$HOME/.swim" ]; then

  #Download the primary swim script
  curl -o $usrDir/swim -s https://raw.githubusercontent.com/dawsonbotsford/swim/master/swim

  #Add swim to path
  chmod +x $usrDir/swim

  #If root's vimrc does not exist
  if [[ ! $(ls -A $HOME/.vimrc 2>/dev/null) ]]; then
    printf "We could not find a .vimrc for you so we made one up!\n"
    touch $HOME/.vimrc
    printf "colorscheme blue" > $HOME/.vimrc
  fi

  mkdir -p $HOME/.swim
  cp $HOME/.vimrc $HOME/.swim/swimrc.main

  printf "calling \"swim add $HOME/.vimrc main\"\n"
  swim add $HOME/.vimrc main

  printf "calling \"swim with main\"\n"
  swim with main

  printf "\nInstall complete!\n\n" | chalk green

else

  printf "Swim already downloaded!\n" | chalk green
  printf "You have the following swim aliases: \n"
  printf "%s\n" "--------------------------" | chalk white

  for file in $HOME/.swim/*
  do
    echo $file | cut -d . -f 3
  done

  printf "%s\n" "--------------------------" | chalk white

fi
