#!/usr/bin/env bash
usrDir=/usr/local/bin

#If swim directory does not exist
if [ ! -d "~/.swim" ]; then
  mkdir ~/.swim
  cp ~/.vimrc ~/.swim/swimrc.main

  #Add swim to path
  curl -o $usrDir/swim -s https://raw.githubusercontent.com/dawsonbotsford/swim/master/swim
  chmod +x $usrDir/swim
  swim add ~/.vimrc main
  swim with main
  echo "Install complete!"
else

  echo "Swim already downloaded! You have the following swim aliases: "
  echo "------------------------------------"

  for file in ~/.swim/*
  do
    echo $file | cut -d . -f 3
  done
o echo "------------------------------------"

fi

