#!/usr/bin/env bash
usrDir=/usr/local/bin

#If swim directory does not exist
if [ ! -d "~/.swim" ]; then

  #Add swim to path
  curl -o $usrDir/swim -s https://raw.githubusercontent.com/dawsonbotsford/swim/master/swim
  chmod +x $usrDir/swim

  #If root's vimrc does not exist
  if [ ! -L "~/.vimrc" ] && [ ! -e "~/.vimrc" ]; then
    echo "We could not find a .vimrc for you so we made one up!"
    echo "colorscheme blue" > ~/.vimrc
  fi

  mkdir -p ~/.swim
  cp ~/.vimrc ~/.swim/swimrc.main

  swim add ~/.vimrc main
  swim with main

  echo "Install complete!"
else

  echo "Swim already downloaded! You have the following swim aliases: "
  echo "------------------------------------"

  for file in ~/.swim/*
  do
    echo $file | cut -d . -f 3
  done
o echo "------------------------------------"

fi

