#!/usr/bin/env bash

function print_help() {
  echo "

Switch vimrc files with one line

Usage:
  swim help                         Show this message
  swim with <alias>                 Change active vimrc file
  swim add <pathToFile> <alias>     Add a swim alias
  swim ls                           List aliased vimrc files
  swim active                       Show currently aliased vimrc

Example:
  swim with main                               Set ~/.swim/.swimrc.main to be your primary .vimrc
  swim with pairing                            Set ~/.swim/.swimrc.pairing to be your primary .vimrc
  swim add ~/dot/.vimrcForPairing pairing     Add an alias called pairing

Setup:
  On install, you should have a swim alias for main. Verify this with \"swim ls\"
  For each alias you would like to add, use \"swim add\".


Report bugs to: https://github.com/dawsonbotsford/swim/issues

Uninstall:
    swim uninstall
"
}

function swim_ls() {
  for file in ~/.swim/*
  do
    echo $file | cut -d . -f 3
  done
}

function get_alias() {
  path = $1
  return head -n1 $path | cut -d \" -f 2 | cut -d \\ -f 2
}

function add_alias() {
  if [ $# -lt 2 ]
  then
    print_help
    exit
  fi
  src=$1
  dest=$2

  cp $1 ~/.swim/swimrc.$2
  echo "swim alias \"$2\" added"
}

function remove_alias() {
  if [ $# -eq 0 ]; then
    print_help
    exit
  fi

  activeFile=$(readlink ~/.vimrc)
  activeAlias=$file | cut -d \. -f 3

  rm ~/.swim/swimrc.$1
  echo "removed alias $1"
}

function backup_vimrc (){
  if [ -a "~/.vimrc" ]; then
    mkdir -p ~/.swim/oldvimrc
    # mv $(readlink ~/.vimrc) ~/.swim/oldvimrc
    mv ~/.vimrc ~/.swim/oldvimrc
  fi
}

#Help conditions
if [ $# -lt 1 ]; then
  print_help
  exit
fi

while [ $# -gt 0 ]; do
  case "$1" in
    uninstall) curl -s https://raw.githubusercontent.com/dawsonbotsford/swim/master/uninstall | bash
      exit;;

    help) print_help
      shift
      exit;;

    ls | -l) shift
      swim_ls;;

    add | -a) add_alias $2 $3
      exit;;

    active | current) file=$(readlink ~/.vimrc)
                      if [ $file ]; then
                        echo $file | cut -d \. -f 3
                      else
                        echo "Error. Swim may not be installed"
                        exit
                      fi
      shift;;

    with | use) shift
      if [ -e "$HOME/.swim/swimrc.$1" ]; then
        if [[ $(readlink ~/.vimrc | cut -d . -f 3) == $1 ]]; then
          echo "That alias is already active."
          exit
        fi
        backup_vimrc
        rm ~/.vimrc
        ln -s ~/.swim/swimrc.$1 ~/.vimrc
        echo "Swimming with: "$1
      else
        echo "alias $1 not found"
        sleep 1
        print_help
      fi
      shift;;

    remove | delete) remove_alias $2
                     exit;;

    *) print_help
      exit;;
  esac
done
