#!/usr/bin/env bash

mv $HOME/.swim/swimrc.main $HOME/.vimrc 2>/dev/null
echo "swimrc.main set to ~/.vimrc"

rm -rf $HOME/.swim 2>/dev/null
echo "swim directory removed from ~"

rm -rf /usr/local/bin/swim 2>/dev/null
echo "swim uninstalled"
